language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install: true
services:
- docker
script: ./mvnw clean install -DskipTests=true -Ddocker.username=ashraf1abdelrasool -Ddocker.password=01120266849
cache:
  directories:
  - $HOME/.m2
  - $TRAVIS_BUILD_DIR/src/main/resources/ui-static/node/node_modules
deploy:
- provider: cloudfoundry
  username: "ashraf4revo@gmail.com"
  password: "01120266849ASHra\\;"
  api: https://api.run.pivotal.io
  organization: 4ashraf4revo
  space: development