spring:
  application:
    name: track
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
logging:
  file: /tmp/${spring.application.name}.log
  level:
    org.springframework: debug
org:
  revo:
    env:
      users:
      - email: revo
        username: revo
        type: '100'
        password: '{bcrypt}$2a$10$55ftqk9N02sq/qFv57HAZO/JgynR2Mg75u05pkMceVAQbvTMXsUI2'